<?php
    echo $valid;
    $form = $this->form;
    $form->prepare();
    echo $this->form()->openTag($form) . PHP_EOL;
        foreach ($form as $Element)
        {
            echo   $Element->getLabel() . PHP_EOL ;
            echo   $this->formElement($Element) . PHP_EOL .'<br>';
            echo   $this->formElementErrors($Element) . PHP_EOL ;

            foreach ($Element as $subElement)
            {
                echo   $subElement->getLabel() . PHP_EOL ;
                echo   $this->formElement($subElement) . PHP_EOL .'<br>';
                echo   $this->formElementErrors($subElement) . PHP_EOL ;
             }
        }
    echo $this->form()->closeTag($form) . PHP_EOL;

